version: '3.6'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./mysql.conf.d:/etc/mysql/mysql.conf.d
      - /data/mysql:/var/lib/mysql
    ports:
      -  "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "YOUR_PASSWORD"
    networks:
      - backend

networks:

  backend:
    name: backend
    driver: bridge
